version: '3.8'

services:
  mssql-2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql2017
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong!Passw0rd 
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql2017_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql2017_data: